/**
 * ShellSort class contains sort and insertionSort methods.
 * 
 * @author Rohan Philip
 * @version 12-17-2011
 */

public class ShellSort
{
    public static void sort(int Arr[])
    {
        int h,i,k;
        int[] sequence = new int[Arr.length/3+1];
        //To generate gap sequence(In this case Knuth's sequence)
        for(i=0,h=1;h<Arr.length;i++,h=3*h+1)
        sequence[i]=h;

        //h-sort for each h generated by gap sequence
        for(--i;i>=0;i--)
            for(k=0;k<sequence[i];k++)  //Loop for insertion sort of each subarray in h-sort
                insertionSort(Arr,k,sequence[i]);
    }

    /**
     * insertionSort() method
     *
     * @param  Arr - the array to be sorted
     * @param  beg - beginning index of array
     * @param  gap - gap between each element
     * @return  nothing
     */
    public static void insertionSort(int[] Arr,int beg,int gap)
    {
        int i,j,item;
        for(j=beg+gap;j<Arr.length;j+=gap)
        {
            item=Arr[j];
            for(i=j-gap ; (i>=beg)&&(item<Arr[i]) ; i-=gap)
                Arr[i+gap]=Arr[i];
            Arr[i+gap]=item;
        }
    }
}
